events {}

http {
    upstream backend {
        server app1:5050;
        server app2:5050;
        server app3:5050;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}